#!/bin/sh

if [ -w /sys/class/backlight/intel_backlight/brightness ] ; then
	DEVICES_BRIGHTNESS=/sys/class/backlight/intel_backlight/brightness
	MAX_BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/max_brightness)
	BAT_BRIGHTNESS=$(( 10 * $MAX_BRIGHTNESS / 100 ))
	AC_BRIGHTNESS=$(( 70 * $MAX_BRIGHTNESS / 100 ))
fi

IF_WIFI=wlp2s0

case "$1" in
	true) # Enable power saving settings on battery
	  # bus
	  for i in /sys/bus/*/devices/*/power/control; do echo auto > $i; done
	  # usb autosuspend
	  for i in /sys/bus/usb/devices/*/power/autosuspend; do echo 1 > $i; done
	  for i in /sys/bus/usb/devices/*/power/control; do echo auto > $i; done
	  # nmi_watchdog -- DISABLED AT KERNEL
	  echo 0 > /proc/sys/kernel/nmi_watchdog
	  # cpu
	  echo 0 > /sys/devices/system/cpu/intel_pstate/min_perf_pct
	  echo 30 > /sys/devices/system/cpu/intel_pstate/max_perf_pct
	  # aspm
	  echo powersave > /sys/module/pcie_aspm/parameters/policy
	  # kernel write mode
	  echo 5 > /proc/sys/vm/laptop_mode
	  echo 90 > /proc/sys/vm/dirty_ratio
	  echo 1 > /proc/sys/vm/dirty_background_ratio
	  echo 60000 > /proc/sys/vm/dirty_expire_centisecs
	  echo 60000 > /proc/sys/vm/dirty_writeback_centisecs
	  # disk powersave
	  # hdparm -S 6 -B 254 -a 2048 /dev/sda &> /dev/null
	  for i in /sys/class/scsi_host/host*/link_power_management_policy; do echo min_power > $i; done
	  # sound card powersave
	  echo 1 > /sys/module/snd_hda_intel/parameters/power_save
	  echo Y > /sys/module/snd_hda_intel/parameters/power_save_controller
	  # wifi powersave
	  iw dev $IF_WIFI set power_save on &> /dev/null
	  # screen powersave
	  for i in $DEVICES_BRIGHTNESS ; do echo $BAT_BRIGHTNESS > $i ; done
	  xset +dpms
	  xset dpms 0 0 120
	  ;;
	false) # Return to default on AC power
	  # bus
	  for i in /sys/bus/*/devices/*/power/control; do echo on > $i; done
	  # usb autosuspend
	  for i in /sys/bus/usb/devices/*/power/autosuspend; do echo 600 > $i; done
	  for i in /sys/bus/usb/devices/*/power/control; do echo auto > $i; done
	  # nmi_watchdog
	  # DISABLED AT KERNEL
	  echo 1 > /proc/sys/kernel/nmi_watchdog
	  # cpu
	  echo 29 > /sys/devices/system/cpu/intel_pstate/min_perf_pct
	  echo 100 > /sys/devices/system/cpu/intel_pstate/max_perf_pct
	  # aspm
	  echo default > /sys/module/pcie_aspm/parameters/policy
	  # kernel write mode
	  echo 0 > /proc/sys/vm/laptop_mode
	  echo 30 > /proc/sys/vm/dirty_ratio
	  echo 30 > /proc/sys/vm/dirty_background_ratio
	  echo 600 > /proc/sys/vm/dirty_expire_centisecs
	  echo 600 > /proc/sys/vm/dirty_writeback_centisecs
	  # disk powersave
	  # hdparm -S 0 -B 254 -a 2048 /dev/sda &> /dev/null
	  for i in /sys/class/scsi_host/host*/link_power_management_policy; do echo max_performance > $i; done
	  # sound card powersave
	  echo 0 > /sys/module/snd_hda_intel/parameters/power_save
	  echo Y > /sys/module/snd_hda_intel/parameters/power_save_controller
	  # wifi powersave
	  iw dev $IF_WIFI set power_save off &> /dev/null
	  # screen powersave
	  for i in $DEVICES_BRIGHTNESS ; do echo $AC_BRIGHTNESS > $i ; done
	  xset -dpms
	  ;;
esac
exit 0
